---
title: 'labeleR: an R package to optimize the generation of collection labels and scientific documents'
tags:
  - R
  - Rmarkdown
  - LaTeX
  - scientific collections
  - scientific events
  - herbaria
  - automation
  - exams
authors:
  - name: Julia G. de Aledo
    orcid: 0000-0001-9065-9316
    affiliation: "1,2,3" # (Multiple affiliations must be quoted)
  - name: Jimena Mateo-Martín
    orcid: 0000-0002-9757-5497
    affiliation: 3
  - name: Francisco Rodríguez-Sánchez
    orcid: 0000-0002-7981-1599
    affiliation: 4
  - name: Ignacio Ramos-Gutiérrez
    orcid: 0000-0002-8675-0114
    affiliation: "3,4"
  
affiliations:
  - name: Estación Biológica de Doñana
    index: 1
  - name: Universidad Rey Juan Carlos
    index: 2
  - name: Universidad Autónoma de Madrid
    index: 3
  - name: Universidad de Sevilla
    index: 4
citation_author: de Aledo et. al.
date: '`r Sys.Date()`'
year: 2025
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
editor_options: 
  markdown: 
    wrap: 72
---

# Summary

`labeleR` is an R package designed to automate the creation of collection labels and documents for scientific events. It simplifies repetitive and time-consuming tasks, offering a practical alternative to manual or costly tools. With `labeleR`, users can generate a wide variety of customizable PDF documents that can also be automatically emailed.

The package provides a set of functions classified into two groups: scientific collections (e.g. labels for herbarium or insects) and scientific events organization (e.g. personal badges, abstract books and certificates of attendance and participation). Starting from a tidy dataset, users can easily customize content, incorporate QR codes, logos, images, and edit their own templates. `labeleR` transforms tedious and repetitive workflows into an efficient, reproducible process, contributing to greater scientific productivity. The package is available under an open-source license and can be freely downloaded from CRAN or the GitHub repository (https://ecologyr.github.io/labeleR/).

# Statement of need

The management and design of scientific labels and event documents is a time-consuming task. Large-scale label generation tools for herbarium and scientific collections (used by institutions such as museums or botanical gardens) are often paid and proprietary software (e.g. @brahms2025 @irisbg2024). Microsoft Excel-Word integration through mailing lists is commonly used at a smaller scale, although still involving paid software with limited large database management capacity. Most free alternatives are not open-source, require installing a program with limited customization, and are often only compatible with Windows operating system (e.g. @elysia2019 @plabel2020), or designed for very specific purposes (e.g. @entomolabels2022 for insects, @lichenlabler2025 for lichens or @herblabel for plant vouchers). Additionally, credentials and certificates for scientific events are either created manually one at a time, through paid online servers, or by hiring an event organization company. To our knowledge, there are no free, customizable tools for the bulk production and distribution of these documents. `labeleR` fills this gap facilitating the creation of scientific collection labels, conference badges, attendance and participation certificates, and abstract books, among others. 






# Package description

The `labeleR` package builds upon the `RMarkdown` ecosystem (@rmarkdown) to generate PDF documents from a tidy data frame in R (Figure 1). `labeleR` functions include three types of arguments: (1) R instructions, such as the data object, paths and file name of the rendered document; (2) “fixed” arguments, text that remains constant across output documents (e.g. event name or image path); (3) “variable” arguments, linked to columns in the dataframe, thus changing between documents (e.g. taxonomic names in labels or attendee names in certificates). A QR code can be included either through a fixed argument or a variable argument, without the need for external software. Users can also edit and adapt the default `RMarkdown` templates provided by the package for their own purposes.



![Figure 1. `labeleR` package workflow. Information stored in a dataset passes through an R function into a parameterized `RMarkdown` file using LaTeX syntax, and is then rendered as PDF. `labeleR` functions accept three argument types: R instructions which specify the dataset, paths to images or add custom templates (in blue); fixed arguments, such as titles or subtitles (in red), and variable arguments, linked to columns of the dataset (in yellow). Users work directly on R to introduce the parameters, while `labeleR` works in the background with markdown and latex to produce the results. Output PDF documents can be automatically emailed to participants.](figures/Fig1.png)

# Documents that can be generated with `labeleR`

## Labels for collections

Appropriate labelling of samples is a fundamental step of the scientific process (i.e., labelling test tubes in laboratories, storing animal or plant materials or displaying collections in museums or botanical gardens). A user-friendly bulk rendering tool is vital for efficiently producing crafted, uniform labels in a reproducible manner. We present three label types: “herbarium” (most complex), “collection” (most aesthetic) and “tinylabels” (compact and simplified, for small insect collections) (Figure 2). These labels can include QR codes (e.g. links to websites, images, or identification codes) without additional tools, making it easy to quickly access and link to external information.


![Figure 2. Examples of the outcomes from each label-related function in `labeleR`. a) Herbarium label: for stored plant vouchers; includes fixed fields (title, subtitle) and variable fields (e.g. taxon, date, coordinates, elevation). The family field is by default capitalized and bold, and species name italic. Size: 4 labels/page. b) Collection label: includes variable fields (first field in italics, second in bold), a customizable logo, font and background colors. Size: 8/page. c) Tinylabel: a simplified collection label with five fields. Size: 16/page. All three functions can include an optional QR code.](figures/Fig2.png)

![Figure 3. Examples of outcomes from each event-related function in `labeleR. a) Abstract book: creates pages with title, authors, affiliations and abstract (variable fields) and can include a table of contents and front page. b) Badges: include name, affiliation, a fixed field for the title, the option to add two images on top, and a dashed line at the bottom for additional hand-written information. c) Attendance certificate: attendee name is a variable field, while event name, signer, and date are fixed fields. d) Participation certificate: includes name, affiliation and title of the communication, and several fixed fields. Both certificate functions allow two images on top, a signature at the bottom, and offer Spanish and English templates.](figures/Fig3.png)

## Documents for scientific events

Scientific events often host a high number of participants, and require the creation of identification badges, abstract books and certificates for attendees and participants. With `labeleR`, templates and code can be customized according to the event, and bulk rendering significantly decreases the amount of time invested in the creation of such materials. Manually delivering attendance and participation certificates is highly time-consuming, but `labeleR` functions allow users to automatically send individual documents to email addresses stored in a column.



# Further applications 

The `labeleR` philosophy is quite simple: creating multiple documents with a common design from a dataset containing the required information. It offers a modular structure that allows for customization and extension for new applications. For instance, the newly added `create_multichoice` function generates multichoice tests randomizing the order of questions and possible answers from a given table (question bank). New developments will happen in the GitHub repository (https://github.com/EcologyR/labeleR) and eventually pushed to CRAN. User feedback and code contributions are welcome in the same repository to keep `labeleR as an open and dynamic tool.


# Acknowledgements

This package has been developed collaboratively between Sevilla and Madrid, with continuous feedback from colleagues in both locations. We acknowledge their input, support and collaboration. We are especially grateful to Manuel Molina for his ideas at `labeleR initial stages. We would like to emphasize that the original idea has been built horizontally among early career researchers. Our work has been possible thanks to the support of the institutions and projects that employ us, and especially by the software-developing workshop (Cádiz, La Muela, 2023) organized by  AEET and funded by US-1381388 grant from Universidad de Sevilla/Junta de Andalucía/FEDER-UE.

J.G.A. was supported by Next Generation EU Investigo contract (URJC-AI-17) and ANTENNA Biodiversa+ and European Commission (PCI2023-146022-2) postdoctoral contract. J.M.M. was supported by the Comunidad de Madrid and Universidad Autónoma de Madrid doctoral grant PEJ-2020-AI/AMB-17551 and research assistant contract PIPF-2022/ECO-24251. F.R.-S. was supported by VI PPIT-US and grants US-1381388 from Universidad de Sevilla/Junta de Andalucía/FEDER-UE and CNS2022-135839 funded by MICIU/AEI/10.13039/501100011033 and by European Union NextGenerationEU/PRTR. I.R.G. was supported by a doctoral  grant at Universidad Autónoma de Madrid and a postdoctoral position at Universidad de Sevilla (CNS2022-135839).

# References

